ui: mocha-bdd
browserify:
  - transform: babelify
browsers:
  - name: firefox
    version: 37..latest
  - name: opera
    version: latest
    platform: Mac 10.10
  - name: chrome
    version: 36..latest
  - name: safari
    version: 7..latest
  - name: ie
    version: 10..latest
  - name: android
    version: '4.4..latest'
  - name: iphone
    version: '6.0..latest'
  - name: MicrosoftEdge
    platform: Windows 10
    version: '20.10240..latest'
